### ISSUE TITLE
[Bug] Cancel in pickfirst sample is not working

### ISSUE THREAD

**Issue by chongkai** [temporalio/samples-go#107]
**Describe the bug**
Not sure if it's a bug. In the pickfirst sample, when the activity with short duration (1s) completes, the workflow cancels but the activity with longer duration (2s) fails to exit.

**To Reproduce**
1. To debug, increase the duration for the 1st activity to 5 seconds:
`f1 := workflow.ExecuteActivity(childCtx, SampleActivity, 0, 5*time.Second)`
2. Add a log to activity code to show when cancel is not working:

> select {
		case <-ctx.Done():
			// We have been cancelled.
			msg := fmt.Sprintf("Branch %d is cancelled.", currentBranchID)
			logger.Info(msg)
			return msg, ctx.Err()
		default:
			logger.Info("not cancelled yet")
			// We are not cancelled yet.
		}

3. f1 is not cancelled until 5 seconds elapsed. worker logs:

> 2021/06/06 09:03:06 INFO  No logger configured for temporal client. Created default one.
2021/06/06 09:03:06 INFO  Started Worker Namespace default TaskQueue pick-first WorkerID 66831@bogon@
2021/06/06 09:03:17 DEBUG ExecuteActivity Namespace default TaskQueue pick-first WorkerID 66831@bogon@ WorkflowType SamplePickFirstWorkflow WorkflowID pick-first_0c62bebb-bada-4110-ba32-26cdd942257b RunID 9663ba53-c621-46aa-b418-4598e1050874 Attempt 1 ActivityID 5 ActivityType SampleActivity
2021/06/06 09:03:17 DEBUG ExecuteActivity Namespace default TaskQueue pick-first WorkerID 66831@bogon@ WorkflowType SamplePickFirstWorkflow WorkflowID pick-first_0c62bebb-bada-4110-ba32-26cdd942257b RunID 9663ba53-c621-46aa-b418-4598e1050874 Attempt 1 ActivityID 6 ActivityType SampleActivity
2021/06/06 09:03:18 INFO  not cancelled yet Namespace default TaskQueue pick-first WorkerID 66831@bogon@ ActivityID 6 ActivityType SampleActivity Attempt 1 WorkflowType SamplePickFirstWorkflow WorkflowID pick-first_0c62bebb-bada-4110-ba32-26cdd942257b RunID 9663ba53-c621-46aa-b418-4598e1050874
2021/06/06 09:03:18 INFO  not cancelled yet Namespace default TaskQueue pick-first WorkerID 66831@bogon@ ActivityID 5 ActivityType SampleActivity Attempt 1 WorkflowType SamplePickFirstWorkflow WorkflowID pick-first_0c62bebb-bada-4110-ba32-26cdd942257b RunID 9663ba53-c621-46aa-b418-4598e1050874
2021/06/06 09:03:18 DEBUG RequestCancelActivity Namespace default TaskQueue pick-first WorkerID 66831@bogon@ WorkflowType SamplePickFirstWorkflow WorkflowID pick-first_0c62bebb-bada-4110-ba32-26cdd942257b RunID 9663ba53-c621-46aa-b418-4598e1050874 Attempt 1 ActivityID 5
2021/06/06 09:03:19 INFO  not cancelled yet Namespace default TaskQueue pick-first WorkerID 66831@bogon@ ActivityID 5 ActivityType SampleActivity Attempt 1 WorkflowType SamplePickFirstWorkflow WorkflowID pick-first_0c62bebb-bada-4110-ba32-26cdd942257b RunID 9663ba53-c621-46aa-b418-4598e1050874
2021/06/06 09:03:20 INFO  not cancelled yet Namespace default TaskQueue pick-first WorkerID 66831@bogon@ ActivityID 5 ActivityType SampleActivity Attempt 1 WorkflowType SamplePickFirstWorkflow WorkflowID pick-first_0c62bebb-bada-4110-ba32-26cdd942257b RunID 9663ba53-c621-46aa-b418-4598e1050874
2021/06/06 09:03:21 INFO  not cancelled yet Namespace default TaskQueue pick-first WorkerID 66831@bogon@ ActivityID 5 ActivityType SampleActivity Attempt 1 WorkflowType SamplePickFirstWorkflow WorkflowID pick-first_0c62bebb-bada-4110-ba32-26cdd942257b RunID 9663ba53-c621-46aa-b418-4598e1050874
2021/06/06 09:03:22 INFO  not cancelled yet Namespace default TaskQueue pick-first WorkerID 66831@bogon@ ActivityID 5 ActivityType SampleActivity Attempt 1 WorkflowType SamplePickFirstWorkflow WorkflowID pick-first_0c62bebb-bada-4110-ba32-26cdd942257b RunID 9663ba53-c621-46aa-b418-4598e1050874
2021/06/06 09:03:22 INFO  Workflow completed. Namespace default TaskQueue pick-first WorkerID 66831@bogon@ WorkflowType SamplePickFirstWorkflow WorkflowID pick-first_0c62bebb-bada-4110-ba32-26cdd942257b RunID 9663ba53-c621-46aa-b418-4598e1050874 Attempt 1

**Expected behavior**
As far as I understand, when workflow calls cancelHandler func, all activities executed with childCtx should be cancelled, and select on ctx.Done() should hit. 

Not sure if I understand correctly.

**Screenshots/Terminal ouput**
If applicable, add screenshots or code blocks to help explain your problem. You can also use [Loom](http://loom.com/) to do short, free video bug reports.

**Versions (please complete the following information where relevant):**
 - OS: Mac
 - Temporal Version: 1.6.0
 - are you using Docker or Kubernetes or building Temporal from source? using Docker compose

**Additional context**

**Comment by chongkai** [comment]
Mentioned in https://pkg.go.dev/go.temporal.io/sdk@v1.6.0/activity, 

> Currently cancellation is delivered only to Activities that call RecordHeartbeat.

Is this the cause?

**Comment by dnr** [comment]
The sample code is calling `RecordHeartbeat`, though, so that's not quite the problem. What appears to be happening is that cancellation is only delivered when a heartbeat is _actually_ sent, and the sdk does batching of heartbeats internally, so that a call to `activity.RecordHeartbeat` doesn't necessarily send a heartbeat. The batching is based on the value of `HeartbeatTimeout`.

You can see this by changing the duration of `f1` to 60 seconds instead of 5 seconds: the activity will be cancelled after around 8 seconds (with `HeartbeatTimeout` set to 10 seconds). If you increase `HeartbeatTimeout` it'll take longer, and if you decrease it, the cancellation will be delivered sooner. You can see the logic here: https://github.com/temporalio/sdk-go/blob/1ec44328977e7bb896d2d405a8f1334120df282a/internal/internal_task_handlers.go#L1628

So this doesn't seem like a bug, though there's probably room to improve the documentation.

**Comment by chongkai** [comment]
Thanks @dnr for your clarification! However, these internals seem a bit obscure to new comers. I submitted a PR (https://github.com/temporalio/samples-go/pull/111) in hopes that it could help others better understand the sample. If it doesn't fit the purpose of the sample, please let me know.
