### ISSUE TITLE
Create an easy way to run all the samples

### ISSUE THREAD

**Issue by markmark206** [temporalio/samples-go#16]
Create `make` target to run all the samples, given a frontend endpoint (e. g. `FRONTEND_ADDRESS=127.0.0.1:7233 make run`). Integrate it with #15.

This will enable two use cases:
1. a dev making change on their machine, and wanting to make sure things still work before submitting a PR
2. CI/CD pipeline running samples against a staging environment as part of its validation of the repo (and, indirectly, of the code deployed to the staging environment).

**Comment by alexshtin** [comment]
This might not be needed if we implement #34 correctly.

**Comment by vitarb** [comment]
Closed as a duplicate
