### ISSUE TITLE
[Feature Request] Porting polling samples from Java examples

### ISSUE THREAD

**Issue by edmondop** [temporalio/samples-go#239]
### Is your feature request related to a problem? Please describe.

Java examples of SDK usage contain an useful example of how to implement polling activities:

- [Frequently Polling Activity](https://github.com/temporalio/samples-java/blob/main/src/main/java/io/temporal/samples/polling/frequent/README.md)
- [Infrequently Polling Activity](https://github.com/temporalio/samples-java/blob/main/src/main/java/io/temporal/samples/polling/infrequent/README.md)
- [Periodic Polling of a sequence of activities](https://github.com/temporalio/samples-java/blob/main/src/main/java/io/temporal/samples/polling/periodicsequence/README.md)

The samples are based on [this](https://community.temporal.io/t/what-is-the-best-practice-for-a-polling-activity/328/2) 
community forum thread.

### Describe the solution you'd like

It would be very useful to bring them to Go examples as well.

**Comment by tsurdilo** [comment]
Thanks @edmondop !

**Comment by edmondop** [comment]
@tsurdilo after reviewing the code in the Java repository (https://github.com/temporalio/samples-java/tree/main/src/main/java/io/temporal/samples/polling), it seems there are three different polling-based scenarios:

- frequent polling activity
- infrequent polling activity
- periodic polling of a sequence of activities

They are organized within a single java package. GO examples have a different organization, i.e. each folder is a single scenario/example. How do you think I should proceed?

- Option A: having a parent folder "polling" containing three subfolders (frequent,infrequent, sequence)
- Option B: having three folders polling_infrequent, polling_frequent, polling_sequence

**Comment by tsurdilo** [comment]
@edmondop i think if it is possible to do Option A that would be better. if its not possible Option B is fine too.

**Comment by edmondop** [comment]
@tsurdilo one additional question, I was looking to https://github.com/temporalio/samples-java/blob/ae302763df044d2d3c62039ac8fc2658fd418daa/src/main/java/io/temporal/samples/polling/periodicsequence/PeriodicPollingStarter.java and I am really struggling to understand how the parent workflow is invoked, given it is not registered.

Nor in the test that workflow is invoked explicitly, only the parent workflow is invoked. I found that kind of confusing, does the parent workflow has a role or is it dead code?

**Comment by edmondop** [comment]
Fixed with #246
