### ISSUE TITLE
[Feature Request] Add a sample with opentelemetry tracing

### ISSUE THREAD

**Issue by nicolasgere** [temporalio/samples-go#269]
It would be awesome to have an example of using opentelemetry tracing with the go sdk.
Thank you!

**Comment by Hades32** [comment]
for reference, this is what we're currently doing and it seems to work fine
```go
import (
	"go.temporal.io/sdk/contrib/opentelemetry"
	"go.temporal.io/sdk/interceptor"
	"go.temporal.io/sdk/client"
)
func init() {
	tracingInterceptor, err := opentelemetry.NewTracingInterceptor(opentelemetry.TracerOptions{})
	options := client.Options{
		Interceptors:       []interceptor.ClientInterceptor{tracingInterceptor},
	}
	c, err := client.Dial(options)
```

**Comment by jjkoh95** [comment]
Hi, the above code works
is there a way to pull trace from workflow context?

**Comment by cretz** [comment]
We usually do not recommend doing this because it can be non-deterministic assuming a worker is setup with OTel. Having said that, you can likely set the `SpanContextKey` option in the `opentelemetry.TracerOptions` and check that key in the workflow context.

**Comment by emanuelef** [comment]
@Hades32 I guess this is what you do on the client side, did you have to add the Otel stanza in the Temporal deploy as documented here : 
https://github.com/temporalio/temporal/blob/master/develop/docs/tracing.md#configuring

**Comment by Hades32** [comment]
@emanuelef no, I didn't change the Temporal deployment. I guess that would only be needed if you want to get detailed information on what's going on inside Temporal. I only cared about knowing which signals were sent, activities and workflows started, etc, and we get all that

**Comment by emanuelef** [comment]
Thanks @Hades32, I'll try to do the same.

**Comment by Quinn-With-Two-Ns** [comment]
Closed by https://github.com/temporalio/samples-go/pull/296
