### ISSUE TITLE
CreateSession doesn't work.

### ISSUE THREAD

**Issue by abhishekgophers** [temporalio/samples-go#302]
### What are you really trying to do?
Sometimes Activities of samples-go/fileprocessing/worker not running in within same worker on local machine.

### Describe the bug
Sometimes Activities with same session within a workflow not running in same worker on local machine.

Worker 1 logs
<img width="1440" alt="Screenshot 2023-08-31 at 7 55 03 PM" src="https://github.com/temporalio/samples-go/assets/122437165/74eab39a-173f-4d25-a35c-e63e3327015c">
Worker 2 logs
<img width="1439" alt="Screenshot 2023-08-31 at 7 55 46 PM" src="https://github.com/temporalio/samples-go/assets/122437165/9205677c-7a24-4e5e-825c-87048fa06cb5">

### Minimal Reproduction
Run multiple workers in different terminals.
https://github.com/temporalio/samples-go/tree/main/fileprocessing/worker/main.go
Run starter to start file processing.
https://github.com/temporalio/samples-go/tree/main/fileprocessing/starter/main.go

### Environment/Versions

- OS and processor: MacBook Pro Apple M2
- Temporal Version: go.temporal.io/sdk v1.23.0
- Are you using Docker or Kubernetes or building Temporal from source?
Building from source https://github.com/temporalio/temporalite main

**Comment by Quinn-With-Two-Ns** [comment]
Maybe I am missing something, but I see no bug here. Each `processFile` call creates [its own session](https://github.com/temporalio/samples-go/blob/cc0790ec7ad44f941e27f9475f2487aeaff72d6c/fileprocessing/workflow.go#L47). Those sessions may be on different workers which is what I see from the logs you posted.

**Comment by abhishekgophers** [comment]
yes, i have read logs incorrectly.
