### ISSUE TITLE
Failed status

### ISSUE THREAD

**Issue by renatocosta** [temporalio/samples-go#347]
Hi,

I need to reprocess some workflows as failed status.
I am looking on https://github.com/temporalio/samples-go/tree/main/recovery.
Can It be for?

**Comment by cretz** [comment]
> I need to reprocess some workflows as failed status.

If a workflow is failed and you need to reprocess it, you will need to start a new instance of it

(closing issue since it's a question, but can ask in [forums](https://community.temporal.io/) or in [Slack](https://t.mp/slack), or comment here if you need to)

**Comment by renatocosta** [comment]
Great.

Thank you for letting me know.
